### ISSUE TITLE
老师您好，打扰了。

### ISSUE THREAD

**Issue by cdefgabguitar** [SE-starshippilot/CSC1001#2]
请问您有港中深csc1001的期末考试题吗？我愿意付费购买，麻烦您了！！！
我的QQ：540904099

**Comment by SE-starshippilot** [comment]
First, I am not a teacher, just a random undergraduate student who has taken the course. There is no way for me to get the exam paper (regardless of which year).
Second, I think your behavior violates our school's honesty code. I will not turn you in this time, but I strongly condemn such behavior. 
Finally, You are welcome to raise questions regarding this course if you like. I can try my best to answer them (or if you're urgent, you can reach out to your professors/TAs/USTFs).

Please be honest, and I wish you good luck in your exams.
